dinner: pizza salad

pizza: cheese topping.peppers
	echo making pizza
	cat cheese topping.peppers > pizza

cheese: 
	echo gooey cheese > cheese

topping.%:
	echo yummy $@ > $@

salad: 
	echo salad is healthy